INSERT INTO USERS (ID, VERSION, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (1, 0, 'admin', 'admin@gmail.com', 'admin', 'ADMIN');
INSERT INTO USERS (ID, VERSION, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (2, 1, 'Sanyi', 'sanyi@gmail.com', 'sanyi', 'USER');
INSERT INTO USERS (ID, VERSION, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (3, 2, 'Zoli', 'pezqaai@gmail.com', 'Zoli', 'USER');
INSERT INTO BUDGETS (ID, VERSION, AVAILABLE_FUNDS, DESCRIPTION, LOCATION, REST, STATUS, TIMESTAMP, USER_ID) VALUES (33, 3, 1000000, 'Minta projekt', 'Budapest', 650000, 'SUBMITED', CURRENT_TIMESTAMP, 3);
INSERT INTO BUDGET_REQUEST (ID, VERSION, PRICE, REQUEST, STATUS, TIMESTAMP, BUDGET_ID, REQUESTS_ID) VALUES (44, 1, 100000, 'FrontEnd fejlesztes', 0, CURRENT_TIMESTAMP, 33, 33);
INSERT INTO BUDGET_REQUEST (ID, VERSION, PRICE, REQUEST, STATUS, TIMESTAMP, BUDGET_ID, REQUESTS_ID) VALUES (45, 1, 250000, 'BackEnd fejlesztes', 0, CURRENT_TIMESTAMP, 33, 33);
--INSERT INTO BUDGETS(ID,VERSION,DESCRIPTION,LOCATION,STATUS,AVAILABLE_FUNDS, TIMESTAMP) VALUES (0,0,'Hálózat fejlesztés(WIFI)','Könyvelő részleg','SUBMITED',100000,CURRENT_TIMESTAMP())