INSERT INTO USERS (ID, VERSION, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (0, 0, 'admin', 'admin@gmail.com', 'admin', 'ADMIN');
INSERT INTO USERS (ID, VERSION, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (1, 1, 'Sanyi', 'sanyi@gmail.com', 'sanyi', 'USER');

INSERT INTO BUDGETS(ID,VERSION,DESCRIPTION,LOCATION,STATUS,AVAILABLE_FUNDS, TIMESTAMP) VALUES (0,0,'Hálózat fejlesztés(WIFI)','Könyvelő részleg','SUBMITED',100000,CURRENT_TIMESTAMP())